<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGR6wM4A\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGR6wM4A/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGR6wM4A.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGR6wM4A\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGR6wM4A\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GR6wM4A',
    'container.build_id' => 'fa8bf3f2',
    'container.build_time' => 1633552555,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGR6wM4A');
