<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9WF83ue\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9WF83ue/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9WF83ue.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9WF83ue\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9WF83ue\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9WF83ue',
    'container.build_id' => 'b23d2766',
    'container.build_time' => 1633200170,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9WF83ue');
