<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxOtf7q\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxOtf7q/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxOtf7q.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxOtf7q\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWxOtf7q\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WxOtf7q',
    'container.build_id' => '5e2b29d8',
    'container.build_time' => 1634122715,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxOtf7q');
